##
## Copyright 2022 Google LLC
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     https://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
[versions]
android-junit5 = "1.3.0"
detekt = "1.23.4"

accessibilityTestFramework = "4.1.0"
android-plugin = "8.2.2"
kspVersion = "1.9.22-1.0.17"

#Compose
material3 = "1.2.0-rc01"
pagingCompose = "3.2.1"
compose-compiler = "1.5.8"
constraintLayoutCompose = "1.0.1"
composeLatest = "1.6.0"
composeBom = "2024.01.00"
activityCompose = "1.8.2"

#Benchmark
benchmark = "1.2.3"
# @keep
compileSdk = "34"

#Coroutines
coroutines = "1.7.3"

#Gradle
gradle = "7.2.0"
androidGradlePlugin = "8.2.2"

guava = "31.1-android"

#Hilt
hilt = "2.48.1"
hiltNavigationCompose = "1.1.0"

junit = "4.13.2"
sonar = "3.3"
kotlin = "1.9.22"
android-test = "8.2.2"
#Core
ktx = "1.12.0"

#Moshi
moshi = "1.15.0"

# @keep
minSdk = "24"
monitor = "1.6.1"
profileInstaller = "1.3.1"


#Network
retrofit = "2.9.0"
retrofitMoshi = "2.9.0"
okhttpLogging = "4.10.0"
gson = "2.10.1"

#Database
room = "2.6.1"
runner = "1.0.1"
# @keep
targetSdk = "34"
testExtJunit = "1.1.5"
tracing = "1.1.0"
uiAutomator = "2.2.0"
viewModelCompose = "2.7.0"
work = "2.9.0"
systemuicontroller = "0.32.0"
timber = "5.0.1"

#Presentation
runtimeCompose = "2.7.0"
lifecycle = "2.7.0"

#ComposeDestination
composeDestination = "1.9.52"

#DataStore
dataStore = "1.0.0"
#Coil
coil = "2.5.0"

#Testing
espresso = "3.5.1"
coreTesting = "2.2.0"

mockk = "1.12.3"

junit5SnapShot = "1.0.0-SNAPSHOT"
uiTestMinifest = "1.5.1"

junitJupiter = "5.9.3"

turbine = "1.0.0"
appcompact = "1.6.1"

immutableList = "0.3.6"
roomCommon = "2.6.1"
material = "1.11.0"

truth = "1.1.5"
mockito = "5.3.1"


[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompact" }
androidx-appcompat-resource = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompact" }
accessibility-test-framework = { module = "com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework", version.ref = "accessibilityTestFramework" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeLatest" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "composeLatest" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "composeLatest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeLatest" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "composeLatest" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeLatest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayoutCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileInstaller" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "systemuicontroller" }

composeDestination = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestination" }
composeDestinationKsp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestination" }

javax-inject = { module = "javax.inject:javax.inject", version = "1" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "runtimeCompose" }

retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofitMoshi" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiCodeGen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }

jUnitJupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
jUnitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit = { module = "junit:junit", version.ref = "junit" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agentJvm = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeLatest" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutableList" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidJunit5-core = { group = "de.mannodermaus.junit5", name = "android-test-core", version.ref = "android-junit5" }
androidJunit5-runner = { group = "de.mannodermaus.junit5", name = "android-test-runner", version.ref = "android-junit5" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

unit-truth = { group = "com.google.truth", name = "truth", version.ref = "truth"}
unit-mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito"}

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version = "1.9.3.0" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-android-test = { id = "com.android.test", version.ref = "android-test" }
sonarCloud = { id = "org.sonarqube", version.ref = "sonar" }
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
